### ISSUE TITLE
Support tests using metatest

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-bash-runner#5]
A test description should look like the following: 

```yaml
examples: 
   - title: when folder exists, it just creates a .gitkeep
     preconditions: 
         - mkdir the_folder
     postconditions: 
         - command_outputs:
              - command: "ls /home/mumuki/the_folder"
              - output: ".gitkeep"
   - title: when folder does not exists, it does not create it
     postconditions: 
         - command_fails: "ls /home/mumuki/the_folder"
              
```

The following matchers should be supported: 

* `commands_outputs`: checks the output of a command
* `command_fails`: that a command fails - returns a non-zero status
* `command_succeeds`: that a command succeeds - returns a zero status
* `command_returns`: that a command returns a specific status-code
